# .goreleaser.yml proposed options for Romie
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
      - dragonfly
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386, arm
      - goos: windows
        goarch: arm, arm64
      - goos: freebsd
        goarch: arm64
      - goos: netbsd
        goarch: arm64
      - goos: dragonfly
        goarch: 386, arm, arm64
    goarm:
      - 6
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

dockers:
  - goos: linux
    goarch: amd64
    binaries:
    - romie
    image_templates:
      - "romie/romie:latest"
      - "romie/romie:{{ .Tag }}"
    skip_push: false
    dockerfile: Dockerfile
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"

